# Generated by Django 5.2.4 on 2025-07-12 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FanZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transport_type', models.CharField(choices=[('tram', 'Tram'), ('bus', 'Bus')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('qr_code_id', models.CharField(max_length=100, unique=True)),
                ('fanzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fanzone')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_routes', to='api.station')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_routes', to='api.station')),
            ],
        ),
    ]
