# Generated by Django 5.2.4 on 2025-07-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Upcoming', max_length=20),
        ),
    ]
