# Generated by Django 5.2.4 on 2025-07-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='fanzone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fanzone_images/'),
        ),
    ]
