# Generated by Django 5.2.4 on 2025-07-17 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_line_id_alter_station_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanzone',
            name='Nearest_Fanzone_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.station'),
        ),
    ]
