# Generated by Django 5.2.4 on 2025-07-21 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fanzone_nearest_fanzone_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfertStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='api.station')),
                ('station_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='api.station')),
            ],
        ),
    ]
