# Generated by Django 5.2.4 on 2025-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_image_fanzone_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanzone',
            name='image',
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
