# Generated by Django 5.2.4 on 2025-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_fanzone_image_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanzone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fanzone_images/'),
        ),
    ]
