# Generated by Django 5.2.4 on 2025-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fanzone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanzone',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
